### ISSUE TITLE
Boros Proxy

### ISSUE THREAD

**Issue by codev911** [AirdropFamilyIDN-V2-0/nodepay#1]
Setelah update malah jadi boros bosku, mungkin diturunin dikit intensitas botnya bos

**Comment by Brajamustii** [comment]
boros gimana tuh

**Comment by codev911** [comment]
biasanya 500 bot sehari gk habis lebih dari 400mb, ini malah belom sehari makan 2gb

**Comment by codev911** [comment]
tadi tak cek emang intensitas pingnya jadi lebih barbar dari yang sebelumnya

**Comment by codev911** [comment]
mungkin bisa diturunin dikit intensitas pingnya bos ? atau dikasih panduan biar bisa di setting buat ini ?

**Comment by codev911** [comment]
![image](https://github.com/user-attachments/assets/31eef971-cdf8-4885-8491-30f3c3ad4d65)
vampir banget proxynya

**Comment by Sigit-AP** [comment]
pke max worker ini mas mkanya boros mungkin di edit pke gpt ilangin max worker sma multithread nya
